### ISSUE TITLE
Does not work for 9th layer

### ISSUE THREAD

**Issue by kriber82** [jdlien/Kaleidoscope-LEDEffect-FunctionalColor#3]
I recently added a 9th layer and the plugin does not work on that layer.
The following change fixed the problem for me:  In `void LEDFunctionalColor::FCPlugin::update(void)` I changed `uint8_t current_layerState` to` uint32_t current_layerState`.
Not sure if this is systematically correct, though.

**Comment by jdlien** [comment]
Thanks for discovering this. I have no idea what you are doing with *nine* layers, but I'm sure I would never have run into this.

At any rate, it looks like you are correct - I'm not sure why I used uint8_t there - maybe some misguided attempt at efficiency, but based on what I've seen in Kaleidoscope, I believe it should be a 32 bit number. The layers aren't numbered but each bit in the uint32 is used as a flag, if I recall. That's why you ran out of flags after 8 layers.
https://github.com/keyboardio/Kaleidoscope/blob/fa34983b5b25156f59fe6dc8b06aae4088053afe/src/layers.cpp

I will make this update the next time I do a commit.

**Comment by atimholt** [comment]
I just ran into the same problem. Glad to see it was resolved so recently.

**Comment by jdlien** [comment]
Sorry it took me an entire year to finally get around fixing this, but the official version that (finally) supports the latest firmware now uses uint32_t to support up to 32 layers.
